### ISSUE TITLE
winetricks missing during the install

### ISSUE THREAD

**Issue by OscarVsp** [kassindornelles/lol-for-linux-bash-installer#3]
Hi ! 
I tried your script on KDE Neon 5.27.
After the "Manual action is required" dialog, the installer does not open and the rest of the installation keep going as if everything were ok. Here are the output of the `leagueinstaller.sh` with the relevant lines:

```
...
[2023-02-19 13:39:07] Creating first-boot script
[2023-02-19 13:43:37] Launching the First-boot script now \n Manual action is required now: \n 1 - We will install DXVK automatically so be patient \n 2 - Once the installer opens please press the install button and wait \n 3 - Once it opens the login screen please close it so we can continue.
./Firstboot.sh: line 12: winetricks: command not found
./Firstboot.sh: line 14: /home/oscarvsp/.local/share/leagueoflegends/wine/bin/wine: No such file or directory
[2023-02-19 13:43:37] Finished first boot
...
```

And them of course if I tried to launch the game it does not work. Here are the output of the `launch-league.sh`:

```
League of legends was detected, running the game...
./Launch.sh: line 11: cd: /home/oscarvsp/.local/share/leagueoflegends/wine/prefix/drive_c/Riot Games/Riot Client: No such file or directory
./Launch.sh: line 12: /home/oscarvsp/.local/share/leagueoflegends/wine/bin/wine: No such file or directory
```

I tried again after installing manually winetrick with a `apt install winetricks`, then wine run at the first boot and the DXVK installation seems ok but once again the installer did not show up and this time the output is (ignoring all the cabextract  warning about the possible extra bytes at the end of the files):

```
Using native override for following DLLs: d3dx9_24 d3dx9_25 d3dx9_26 d3dx9_27 d3dx9_28 d3dx9_29 d3dx9_30
Executing wine regedit C:\windows\Temp\override-dll.reg
sh: 0: getcwd() failed: No such file or directory
wine: could not open working directory L"unix\\", starting in the Windows directory.
Executing wine64 regedit C:\windows\Temp\override-dll.reg
Using native override for following DLLs: d3dx9_31 d3dx9_32 d3dx9_33 d3dx9_34 d3dx9_35 d3dx9_36 d3dx9_37
Executing wine regedit C:\windows\Temp\override-dll.reg
sh: 0: getcwd() failed: No such file or directory
wine: could not open working directory L"unix\\", starting in the Windows directory.
Executing wine64 regedit C:\windows\Temp\override-dll.reg
Using native override for following DLLs: d3dx9_38 d3dx9_39 d3dx9_40 d3dx9_41 d3dx9_42 d3dx9_43
Executing wine regedit C:\windows\Temp\override-dll.reg
sh: 0: getcwd() failed: No such file or directory
wine: could not open working directory L"unix\\", starting in the Windows directory.
Executing wine64 regedit C:\windows\Temp\override-dll.reg
./Firstboot.sh: line 14: /home/oscarvsp/.local/share/leagueoflegends/wine/bin/wine: No such file or directory
```

I hope this can help you. The idea of your script is very nice.
Tell me if I can try something else to figure out what is going wrong

**Comment by kassindornelles** [comment]
this is ubuntu 22.04? will try to repro in a virtual machine

**Comment by kassindornelles** [comment]
yeah the script is pretty broken on KDE Neon, i'm working on it in this [branch](https://github.com/kassindornelles/lol-for-linux-bash-installer/tree/kde-neon-is-stupid).

not ready to use it yet.

**Comment by kassindornelles** [comment]
@OscarVsp i tested in my virtual machine and looks like its fixed here

Here some tips for you to try again:

- Be sure that you have 32 bit support enabled in your distro:
```sudo dpkg --add-architecture i386```
```sudo apt update```

- Be sure to have both 32 and 64 bit installed system wide:
```sudo apt install wine```

- Be sure to have winetricks installed
```sudo apt install winetricks```

![image](https://user-images.githubusercontent.com/40970965/219963356-3f675ab2-cf68-4b6f-bf5d-10626e52f2ca.png)

**Comment by kassindornelles** [comment]
All changes (that made it work for me in my VM) got merged into the main branch, waiting for your feedback @OscarVsp before closing.

**Comment by OscarVsp** [comment]
Thank for the update !

I had some difficulty installing the 32bit version of wine but this seems to be a known issue with KDE Neon and I finally found the solution on [WineHQ website](https://wiki.winehq.org/Ubuntu).

Once both 64bit and 32bit version of wine were installed, your script works perfectly!
Thank you!
